- hosts: all
  tasks:
  - name: install example application
    copy: 
      src: ansible_test_app 
      dest: /tmp/
      owner: root
      group: root
  - name: ansible pull changes
    cron:
      name: "check ansible"
      minute: "00,10,20,30,40,50"
      hour: "*"
      job: "/bin/ansible-pull -U https://github.com/tr-patrick/ansible-practice -i hosts"
